branch-defaults:
  master:
    environment: manoj-manja
    group_suffix: null
environment-defaults:
  django-tutorial:
    branch: null
    repository: null
global:
  application_name: ebdjango
  branch: null
  default_ec2_keyname: Libratech_GIT
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
